#!/usr/bin/env python3
"""
Wolf → AI-Trader Bridge
Reads Wolf scanner output, publishes top signals to AI-Trader as strategy posts.

Usage:
    python3 wolf_to_trader.py                    # Publish today's top 3
    python3 wolf_to_trader.py --top 5            # Publish top 5
    python3 wolf_to_trader.py --dry-run          # Preview without publishing
    python3 wolf_to_trader.py --file path.json   # Use specific Wolf output file
"""
import json
import sys
import os
import glob
from datetime import datetime
from pathlib import Path

SKILL_DIR = Path.home() / ".hermes" / "skills" / "trading" / "ai-trader"
SCRIPTS_DIR = SKILL_DIR / "scripts"
WOLF_OUTPUT = Path.home() / ".hermes" / "skills" / "trading" / "wolf-trading-agent" / "output"

sys.path.insert(0, str(SCRIPTS_DIR))
from ai_trader_client import ApiClient, AiTraderError


def find_latest_wolf_output() -> dict:
    files = sorted(glob.glob(str(WOLF_OUTPUT / "wolf_enhanced_*.json")), reverse=True)
    if not files:
        print("No Wolf output files found in", WOLF_OUTPUT)
        sys.exit(1)
    print(f"Reading: {files[0]}")
    with open(files[0]) as f:
        return json.load(f)


def format_strategy(signal: dict) -> tuple:
    ticker = signal.get("ticker", "?")
    mentions = signal.get("mentions", 0)
    sources = signal.get("sources", [])
    sentiment = signal.get("total_sentiment", 0)
    avg_sentiment = sentiment / max(mentions, 1)

    if avg_sentiment > 0.3:
        direction, emoji = "BULLISH", "🟢"
    elif avg_sentiment < -0.3:
        direction, emoji = "BEARISH", "🔴"
    else:
        direction, emoji = "NEUTRAL", "🟡"

    source_str = ", ".join(sources) if sources else "mixed"
    title = f"Wolf Signal: {emoji} {ticker} — {direction} ({mentions} mentions)"
    content = f"""🐺 **Wolf Trading Agent — Daily Signal**

**Ticker:** {ticker}
**Direction:** {direction}
**Mentions:** {mentions} across {source_str}
**Avg Sentiment:** {avg_sentiment:.2f}

**Analysis:**
Social sentiment scan across Reddit, Twitter/X, and financial news detected {mentions} mentions of {ticker} with {direction.lower()} bias.

**Sources:** {source_str}

*This signal is generated by the Wolf Trading Agent — a social sentiment scanner that monitors Reddit, Twitter, and GNews for emerging stock momentum. Not financial advice.*"""

    return title, content, [ticker], ["wolf-agent", "sentiment", direction.lower(), source_str]


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Wolf → AI-Trader bridge")
    parser.add_argument("--top", type=int, default=3, help="Number of top signals to publish")
    parser.add_argument("--dry-run", action="store_true", help="Preview without publishing")
    parser.add_argument("--file", help="Specific Wolf output JSON file")
    args = parser.parse_args()

    if args.file:
        with open(args.file) as f:
            data = json.load(f)
    else:
        data = find_latest_wolf_output()

    signals = data.get("signals", [])
    if not signals:
        print("No signals in Wolf output")
        return

    signals.sort(key=lambda s: abs(s.get("total_sentiment", 0)) * s.get("mentions", 1), reverse=True)
    top = signals[:args.top]

    print(f"\n📊 Top {len(top)} Wolf signals:\n")
    for s in top:
        ticker = s.get("ticker", "?")
        mentions = s.get("mentions", 0)
        sent = s.get("total_sentiment", 0) / max(mentions, 1)
        direction = "🟢" if sent > 0.3 else "🔴" if sent < -0.3 else "🟡"
        print(f"  {direction} {ticker:8s} mentions={mentions:3d}  sentiment={sent:+.2f}")

    if args.dry_run:
        print("\n(dry run — not publishing)")
        return

    client = ApiClient()
    published = 0
    for s in top:
        title, content, symbols, tags = format_strategy(s)
        try:
            result = client.publish_strategy(market="us-stock", title=title, content=content, symbols=symbols, tags=tags)
            print(f"\n  ✅ Published: {title[:60]}")
            published += 1
        except AiTraderError as exc:
            print(f"\n  ❌ Failed: {exc}")

    print(f"\n🏁 Published {published}/{len(top)} signals to AI-Trader")


if __name__ == "__main__":
    main()
